### PR TITLE
refactor: Remove client.Reset

### PR DESCRIPTION
**Pull request by willbeason**
Now that gatekeeper no longer uses it, there are no callers. All tests
have previously been migrated off to avoid potential crosstalk.

This makes the implementation work for rego compilation
sharding/optimization significantly easier.

Signed-off-by: Will Beason <willbeason@google.com>

### CODE REVIEW

**Comment by willbeason** [comment]
Ignore the gatekeeper failure - that is fixed by https://github.com/open-policy-agent/gatekeeper/pull/1762

**Review by maxsmythe — APPROVED** [review]
LGTM

**Review by sozercan — APPROVED** [review]
LGTM

**Comment by ritazh** [comment]
gatekeeper_test is failing

**Comment by willbeason** [comment]
> gatekeeper_test is failing

This is expected and is fixed by the PR linked in the above comment.

**Pull request merged**
