### PR TITLE
Upgrade go dependencies

### PR DESCRIPTION
**Pull request by willbeason**
Upgrade core k8s libraries to be the same as the ones required for
gatekeeper. Also upgrade others.

No changes to our code required.

Signed-off-by: Will Beason <willbeason@google.com>

### CODE REVIEW

**Review by maxsmythe — APPROVED** [review]
LGTM

**Review by srenatus — APPROVED** [review]
Looks good to me. The OPA bump will get you https://github.com/open-policy-agent/opa/issues/2092, which has mentioned some GK security audit from the past, just a heads-up. You may want to have a closer look.

**Comment by sozercan** [comment]
@willbeason looks like there is vendor inconsistency in gk test

**Comment by willbeason** [comment]
> @willbeason looks like there is vendor inconsistency in gk test

That's because of the changes to frameworks/. As the dependencies of frameworks/ change, if frameworks/ is the only reason they are included in gatekeeper/ then this inconsistency will arise. There isn't a (sane) way to do this without breaking that test.

**Comment by willbeason** [comment]
> @willbeason I see. Is the plan to open a corresponding PR to vendor latest frameworks into GK once this PR merges?

Yep!

**Review by sozercan — APPROVED** [review]

**Comment by willbeason** [comment]
I'll merge in a couple hours - I'll have time then to send out a PR that resolves the resulting gatekeeper conflicts.

**Comment by willbeason** [comment]
Merging now; I'll send out a PR for gatekeeper momentarily.

**Pull request merged**
