### PR TITLE
chore: bumping opa 0.66.0 to 0.67.0

### PR DESCRIPTION
**Pull request by JaydipGabani**

### CODE REVIEW

**Review by sozercan — APPROVED** [review]

**Comment by ritazh** [comment]
Testing failures:
```
go test -mod vendor ./pkg/... ./apis/... ./cmd/gator/... -race -bench . -coverprofile cover.out
# go.opentelemetry.io/otel/sdk/metric
Error: vendor/go.opentelemetry.io/otel/sdk/metric/meter.go:63:22: cannot use (*meter)(nil) (value of type *meter) as "go.opentelemetry.io/otel/metric".Meter value in variable declaration: *meter does not implement "go.opentelemetry.io/otel/metric".Meter (missing method Float64Gauge)
Error: vendor/go.opentelemetry.io/otel/sdk/metric/provider.go:101:9: cannot use mp.meters.Lookup(s, func() *meter {…}) (value of type *meter) as "go.opentelemetry.io/otel/metric".Meter value in return statement: *meter does not implement "go.opentelemetry.io/otel/metric".Meter (missing method Float64Gauge)
# github.com/open-policy-agent/gatekeeper/v3/pkg/gator
Error: pkg/gator/client.go:32:63: undefined: drivers.QueryOpt
# github.com/open-policy-agent/gatekeeper/v3/pkg/target [github.com/open-policy-agent/gatekeeper/v3/pkg/target.test]
Error: pkg/target/target_integration_test.go:471:47: undefined: drivers.Tracing
Error: pkg/target/target_integration_test.go:500:49: undefined: drivers.Tracing
Error: pkg/target/target_integration_test.go:513:49: undefined: drivers.Tracing
```

**Comment by JaydipGabani** [comment]
Otel test failures should be fixed once we bump [sdk/metric in go.mod](https://github.com/open-policy-agent/gatekeeper/blob/master/go.mod#L30) on gatekeeper with opa bump.

**Comment by ritazh** [comment]
> Otel test failures should be fixed once we bump [sdk/metric in go.mod](https://github.com/open-policy-agent/gatekeeper/blob/master/go.mod#L30) on gatekeeper with opa bump.

can you push a GK PR with the proposed change so we can validate the bump fixes the issue? thank you!

**Comment by JaydipGabani** [comment]
@ritazh Bumping otel in this PR - [gatekeeper/#3469](https://github.com/open-policy-agent/gatekeeper/pull/3469)

**Review by ritazh — APPROVED** [review]
LGTM

**Pull request merged**
