### PR TITLE
Update API structs to not use slice of pointer.

### PR DESCRIPTION
**Pull request by briantkennedy**
https://github.com/open-policy-agent/gatekeeper/issues/188

### CODE REVIEW

**Comment by sozercan** [comment]
also related to https://github.com/kubernetes/kubernetes/issues/99240?

**Review by sozercan — APPROVED** [review]
Thank you! LGTM

**Comment by briantkennedy** [comment]
Accidentally closed, I don't believe I have permission to merge, what's the process for this?

**Comment by maxsmythe** [comment]
Let us know when ready to merge, usually we merge after maintainers from 2 different orgs LGTM

**Review by maxsmythe — APPROVED** [review]
LGTM

**Comment by maxsmythe** [comment]
Assuming we're good to merge, since you were trying to do so ;)

**Pull request merged**
