### PR TITLE
Remove storage calls from local.Driver.alterModules

### PR DESCRIPTION
**Pull request by davis-haba**
Remove UpsertPolicy/DeletePolicy from local.driver.altermodules

https://github.com/open-policy-agent/frameworks/issues/156

### CODE REVIEW

**Comment by willbeason** [comment]
FYI - you'll need to add DCO for this commit (the failure has the exact command to fix it for this).

In the long term, you may want to set up a commit hook that automatically appends the signature line so you never forget DCO.

**Comment by davis-haba** [comment]
Thanks Will. I updated the commit with the signature.

**Review by willbeason — APPROVED** [review]
Great!

**Comment by sozercan** [comment]
@davis-haba looks like unit tests are failing

**Review by sozercan — APPROVED** [review]

**Comment by willbeason** [comment]
Merging. I'll update my current test PR in gatekeeper so it includes these changes, to see if it catches any problems.

**Pull request merged**
