### PR TITLE
chore: Upgrade to k8s v0.26.1

### PR DESCRIPTION
**Pull request by maxsmythe**
Signed-off-by: Max Smythe <smythe@google.com>

### CODE REVIEW

**Comment by maxsmythe** [comment]
@sozercan @ritazh ready for review. For some reason G8r is no longer auto-pulling the yaml file, but adding an import to main.go in G8r should fix that.

**Comment by ritazh** [comment]
Re-running gatekeeper_test
> unable to install CRDs onto control plane: unable to read CRD files

**Comment by ritazh** [comment]
> For some reason G8r is no longer auto-pulling the yaml file, but adding an import to main.go in G8r should fix that.

@maxsmythe which yaml file are you referring to?

**Comment by maxsmythe** [comment]
@ritazh The YAML that's causing the gatekeeper test to fail:

https://github.com/open-policy-agent/frameworks/blob/master/constraint/deploy/crds.yaml

For some reason the gomod trick of putting the file next to a [golang file](https://github.com/open-policy-agent/frameworks/blob/master/constraint/deploy/tools.go) stopped working with this change, but can be fixed if we import the stub golang file.

**Review by ritazh — APPROVED** [review]
LGTM
Thanks for fixing this!

**Comment by sozercan** [comment]
@maxsmythe is it due to https://github.com/open-policy-agent/gatekeeper/pull/2541/files#diff-16240bfda0b416c9b02e1495bb80506c3ab4b54750e087dc3273a42ed5f13ff3 got removed?

**Comment by sozercan** [comment]
https://github.com/open-policy-agent/gatekeeper/pull/2558

**Review by sozercan — APPROVED** [review]
merged GK PR, rerunning CI. LGTM

**Comment by maxsmythe** [comment]
Thanks!

**Pull request merged**
