### PR TITLE
fix: setting default value for enforcement action

### PR DESCRIPTION
**Pull request by JaydipGabani**
Signed-off-by: Jaydip Gabani <gabanijaydip@gmail.com>

Output after this change for `k get constraint`
```
NAME               ENFORCEMENT-ACTION   TOTAL-VIOLATIONS
pod-must-have-gk   deny                 
```

### CODE REVIEW

**Comment by JaydipGabani** [comment]
After this PR is merged, we can update frameworks in gatekeeper and fix [#gatekeeper/1995](https://github.com/open-policy-agent/gatekeeper/issues/1995)

**Comment by maxsmythe** [comment]
@sozercan Do you have a design for per-EP enforcement action? I am concerned that, until we know the design, making this change may make our lives more difficult.

**Comment by maxsmythe** [comment]
(per comment on the issue)

**Comment by sozercan** [comment]
@maxsmythe proposal is here: https://docs.google.com/document/d/1QIABjZN9B8oBZF5mm1hz5IhpTGulm1jTNn20nYIF-Hc/edit#

**Review by maxsmythe — APPROVED** [review]
LGTM!

**Comment by sozercan** [comment]
@JaydipGabani looks like UT is failing, is that expected?

**Comment by JaydipGabani** [comment]
@sozercan I am trying to figure out why UT is failing, it shouldn't as far as I remember.

**Comment by JaydipGabani** [comment]
@sozercan mergning this, fixed the UT.

**Pull request merged**
