### PR TITLE
feat: remove cel driver from framework

### PR DESCRIPTION
**Pull request by abhipatnala**

### CODE REVIEW

**Comment by maxsmythe** [comment]
LGTM, pending approval of the Gatekeeper PR (modulo import override) so that the code moved to G8r can be merged as a fast-follow.

**Review by ritazh — APPROVED** [review]
LGTM

**Review by JaydipGabani — APPROVED** [review]

**Comment by maxsmythe** [comment]
Waiting on https://github.com/open-policy-agent/gatekeeper/pull/3570 approval to merge

**Comment by ritazh** [comment]
@maxsmythe does this PR LGTY? we need this PR to merge first so go.mod in https://github.com/open-policy-agent/gatekeeper/pull/3570 can point to the latest commit

**Review by maxsmythe — APPROVED** [review]
LGTM

**Pull request merged**
